### ISSUE TITLE
How about dice loss for multi-classes problem?

### ISSUE THREAD

**Issue by John1231983** [luiscarm9/Volumetric-Multimodality-Neural-Network#1]
Thanks for sharing your work!

As I know, the dice loss is just for two classes segmentation problem. I am working in four classes segmentation problem, such as brain segmentation. Do you have any suggestion to change your dice loss to adapt with my problem? Thanks

**Comment by luiscarm9** [comment]
You can try to implement the Generalized Dice Loss (GDL) on Caffe.
[Generalised Dice overlap as a deep learning loss](https://arxiv.org/pdf/1707.03237v3.pdf)

**Comment by John1231983** [comment]
Thanks. Have you tried it in caffe? How much gain can we achieve in comparison with Softmaxwithloss?

**Comment by luiscarm9** [comment]
No. The problem with SoftMaxWithLoss is that it can't deal with class imbalance, we tried that in our problem but the performance was way lower than using dice loss.

**Comment by John1231983** [comment]
Thanks. But we can use weightded softmaxwithloss to deal it. Dice loss often works in binary classification problem. I did not find any source code using dice for multiple class problem in caffe
